### ISSUE TITLE
Is there a font generator here?

### ISSUE THREAD

**Issue by mbgroot** [teeminus/NoTouchScreenFirmware#1] opened 2021-01-14 08:14 UTC
![image](https://user-images.githubusercontent.com/7091348/104562530-4e976980-566a-11eb-9926-9c9be40fb28a.png)
On the TFT24 and klipper i see this

**Comment by teeminus** [comment] 2021-01-14 09:43
As far as I could see from the code, the character generator is implemented. I don't know if it is working, but after dumping the commands/data send to the display by klipper I only see the custom characters beeing programmed but not used.

Have you:
1) tried entering the menu by pressing the knob? How does that look?
2) tried restarting klipper host and firmware after flashing the LCD?

This is how my TFT35v3 looks with klipper:
![fr_821_sm](https://user-images.githubusercontent.com/32164856/104573425-294c3080-5655-11eb-82c2-f2aa373cad26.jpg)
![fr_820_sm](https://user-images.githubusercontent.com/32164856/104573441-2bae8a80-5655-11eb-9e6f-6a405840d9a4.jpg)

**Comment by mbgroot** [comment] 2021-01-14 09:47
1. in the menu no font too.
2. yes, i'm restart.

**Comment by teeminus** [comment] 2021-01-14 12:10
Maybe the issue is caused by the fullscreen mode. I disabled that, please try again. If that does not work, I don't any more ideas why the firmware is not working for the TFT24.

**Comment by mbgroot** [comment] 2021-01-14 12:15
did not help :(

**Comment by teeminus** [comment] 2021-01-14 12:39
If have no idea what could cause the problems. The TFT24 uses a different (and slower) MSU than the TFT35. It could be timing related (the TFT24 has no fsmc high speed module). You could try increasing the delays in the klipper ST7920 driver.

**Comment by teeminus** [comment] 2021-02-03 07:20
The ST7920 driver has been reimplemented from scratch. The problem should be fixed now.

**Closed by teeminus** 2021-02-03 07:20 UTC
